# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_managewidget(object):
    def setupUi(self, managewidget):
        managewidget.setObjectName("managewidget")
        managewidget.resize(676, 618)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(managewidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(managewidget)
        self.label.setMinimumSize(QtCore.QSize(30, 30))
        self.label.setMaximumSize(QtCore.QSize(30, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/images/search.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.searchtext = QtWidgets.QLineEdit(managewidget)
        self.searchtext.setStyleSheet("font:11pt \"思源黑体 CN Regular\";")
        self.searchtext.setText("")
        self.searchtext.setFrame(False)
        self.searchtext.setObjectName("searchtext")
        self.horizontalLayout.addWidget(self.searchtext)
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.addbtn = QtWidgets.QPushButton(managewidget)
        self.addbtn.setMinimumSize(QtCore.QSize(30, 30))
        self.addbtn.setMaximumSize(QtCore.QSize(30, 30))
        self.addbtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addbtn.setIcon(icon)
        self.addbtn.setIconSize(QtCore.QSize(30, 30))
        self.addbtn.setFlat(True)
        self.addbtn.setObjectName("addbtn")
        self.horizontalLayout.addWidget(self.addbtn)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 10)
        self.horizontalLayout.setStretch(4, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(managewidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: 0px solid\n"
"}\n"
"\n"
"QScrollBar::vertical {\n"
"    border: none;\n"
"    width: 10px;\n"
"    margin: 3px 0 3px 0;\n"
"}\n"
"\n"
"QScrollBar::horizontal {\n"
"    border: none;\n"
"    height: 10px;\n"
"    margin: 0 3px 0 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical,\n"
"QScrollBar::handle:horizontal {\n"
"    background: #F2F2F2;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 0px solid grey;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 0px solid grey;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: #ffffff;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 654, 564))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userslayout = QtWidgets.QGridLayout()
        self.userslayout.setHorizontalSpacing(0)
        self.userslayout.setObjectName("userslayout")
        self.verticalLayout.addLayout(self.userslayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 530, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(managewidget)
        QtCore.QMetaObject.connectSlotsByName(managewidget)

    def retranslateUi(self, managewidget):
        _translate = QtCore.QCoreApplication.translate
        managewidget.setWindowTitle(_translate("managewidget", "Form"))
import assets.assets_rc
