# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newdialog(object):
    def setupUi(self, newdialog):
        newdialog.setObjectName("newdialog")
        newdialog.resize(272, 132)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(newdialog.sizePolicy().hasHeightForWidth())
        newdialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        newdialog.setWindowIcon(icon)
        newdialog.setStyleSheet("background: #ffffff")
        self.verticalLayout = QtWidgets.QVBoxLayout(newdialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(newdialog)
        self.label.setMinimumSize(QtCore.QSize(45, 0))
        self.label.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label.setStyleSheet("font:10pt \"思源黑体 CN Regular\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.name = QtWidgets.QLineEdit(newdialog)
        self.name.setMinimumSize(QtCore.QSize(0, 0))
        self.name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.name.setStyleSheet("font:9pt \"思源黑体 CN Regular\";")
        self.name.setText("")
        self.name.setObjectName("name")
        self.horizontalLayout_2.addWidget(self.name)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(newdialog)
        self.label_2.setMinimumSize(QtCore.QSize(45, 0))
        self.label_2.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_2.setStyleSheet("font:10pt \"思源黑体 CN Regular\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imagepath = QtWidgets.QLineEdit(newdialog)
        self.imagepath.setMinimumSize(QtCore.QSize(0, 0))
        self.imagepath.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imagepath.setStyleSheet("font:9pt \"思源黑体 CN Regular\";")
        self.imagepath.setText("")
        self.imagepath.setObjectName("imagepath")
        self.horizontalLayout.addWidget(self.imagepath)
        self.imagepathbtn = QtWidgets.QPushButton(newdialog)
        self.imagepathbtn.setMinimumSize(QtCore.QSize(33, 0))
        self.imagepathbtn.setMaximumSize(QtCore.QSize(33, 16777215))
        self.imagepathbtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imagepathbtn.setIcon(icon1)
        self.imagepathbtn.setAutoDefault(False)
        self.imagepathbtn.setFlat(True)
        self.imagepathbtn.setObjectName("imagepathbtn")
        self.horizontalLayout.addWidget(self.imagepathbtn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.confirmbtn = QtWidgets.QPushButton(newdialog)
        self.confirmbtn.setStyleSheet("background-color: #98C075;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 10px;\n"
"font: 75 9pt \"思源黑体 CN Bold\";")
        self.confirmbtn.setObjectName("confirmbtn")
        self.horizontalLayout_4.addWidget(self.confirmbtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.cancelbtn = QtWidgets.QPushButton(newdialog)
        self.cancelbtn.setStyleSheet("background-color: #ED7161;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 10px;\n"
"font: 75 9pt \"思源黑体 CN Bold\";")
        self.cancelbtn.setObjectName("cancelbtn")
        self.horizontalLayout_4.addWidget(self.cancelbtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 2)
        self.horizontalLayout_4.setStretch(4, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(newdialog)
        QtCore.QMetaObject.connectSlotsByName(newdialog)

    def retranslateUi(self, newdialog):
        _translate = QtCore.QCoreApplication.translate
        newdialog.setWindowTitle(_translate("newdialog", "添加"))
        self.label.setText(_translate("newdialog", "姓名"))
        self.label_2.setText(_translate("newdialog", "照片"))
        self.confirmbtn.setText(_translate("newdialog", "确定"))
        self.cancelbtn.setText(_translate("newdialog", "取消"))
import assets.assets_rc
