# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userwidget(object):
    def setupUi(self, userwidget):
        userwidget.setObjectName("userwidget")
        userwidget.resize(155, 165)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(userwidget.sizePolicy().hasHeightForWidth())
        userwidget.setSizePolicy(sizePolicy)
        userwidget.setMinimumSize(QtCore.QSize(155, 165))
        userwidget.setMaximumSize(QtCore.QSize(160, 165))
        self.verticalLayout = QtWidgets.QVBoxLayout(userwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image = QtWidgets.QGraphicsView(userwidget)
        self.image.setMinimumSize(QtCore.QSize(132, 100))
        self.image.setMaximumSize(QtCore.QSize(132, 100))
        self.image.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.image.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nametext = QtWidgets.QLineEdit(userwidget)
        self.nametext.setEnabled(False)
        self.nametext.setStyleSheet("font:9pt \"思源黑体 CN Regular\";")
        self.nametext.setText("")
        self.nametext.setObjectName("nametext")
        self.horizontalLayout.addWidget(self.nametext)
        self.editbtn = QtWidgets.QPushButton(userwidget)
        self.editbtn.setMinimumSize(QtCore.QSize(30, 30))
        self.editbtn.setMaximumSize(QtCore.QSize(30, 30))
        self.editbtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editbtn.setIcon(icon)
        self.editbtn.setFlat(True)
        self.editbtn.setObjectName("editbtn")
        self.horizontalLayout.addWidget(self.editbtn)
        self.deletebtn = QtWidgets.QPushButton(userwidget)
        self.deletebtn.setMinimumSize(QtCore.QSize(30, 30))
        self.deletebtn.setMaximumSize(QtCore.QSize(30, 30))
        self.deletebtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deletebtn.setIcon(icon1)
        self.deletebtn.setIconSize(QtCore.QSize(30, 30))
        self.deletebtn.setFlat(True)
        self.deletebtn.setObjectName("deletebtn")
        self.horizontalLayout.addWidget(self.deletebtn)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(userwidget)
        QtCore.QMetaObject.connectSlotsByName(userwidget)

    def retranslateUi(self, userwidget):
        _translate = QtCore.QCoreApplication.translate
        userwidget.setWindowTitle(_translate("userwidget", "Form"))
import assets.assets_rc
