# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadingwindow(object):
    def setupUi(self, loadingwindow):
        loadingwindow.setObjectName("loadingwindow")
        loadingwindow.resize(350, 87)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(loadingwindow.sizePolicy().hasHeightForWidth())
        loadingwindow.setSizePolicy(sizePolicy)
        loadingwindow.setMinimumSize(QtCore.QSize(350, 50))
        loadingwindow.setMaximumSize(QtCore.QSize(350, 87))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        loadingwindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(loadingwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setStyleSheet("font:10pt \"思源黑体 CN Regular\";\n"
"background: white")
        self.text.setText("")
        self.text.setObjectName("text")
        self.horizontalLayout.addWidget(self.text)
        loadingwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(loadingwindow)
        QtCore.QMetaObject.connectSlotsByName(loadingwindow)

    def retranslateUi(self, loadingwindow):
        _translate = QtCore.QCoreApplication.translate
        loadingwindow.setWindowTitle(_translate("loadingwindow", "加载中"))
import assets.assets_rc
