# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logs.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logswidget(object):
    def setupUi(self, logswidget):
        logswidget.setObjectName("logswidget")
        logswidget.resize(676, 618)
        self.verticalLayout = QtWidgets.QVBoxLayout(logswidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(logswidget)
        self.label.setStyleSheet("font:10pt \"思源黑体 CN Regular\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.infobtn = QtWidgets.QPushButton(logswidget)
        self.infobtn.setEnabled(False)
        self.infobtn.setMinimumSize(QtCore.QSize(100, 32))
        self.infobtn.setMaximumSize(QtCore.QSize(100, 32))
        self.infobtn.setStyleSheet("QPushButton{\n"
"  padding: 5px 10px;\n"
"  border-radius: 7px;\n"
"  font: 75 9pt \"思源黑体 CN Bold\";\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"  background-color: rgb(152, 192, 117);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.infobtn.setFlat(True)
        self.infobtn.setObjectName("infobtn")
        self.horizontalLayout.addWidget(self.infobtn)
        self.warningbtn = QtWidgets.QPushButton(logswidget)
        self.warningbtn.setEnabled(True)
        self.warningbtn.setMinimumSize(QtCore.QSize(100, 32))
        self.warningbtn.setMaximumSize(QtCore.QSize(100, 32))
        self.warningbtn.setStyleSheet("QPushButton{\n"
"  padding: 5px 10px;\n"
"  border-radius: 7px;\n"
"  font: 75 9pt \"思源黑体 CN Bold\";\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"  background-color: rgb(255, 204, 102);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.warningbtn.setFlat(True)
        self.warningbtn.setObjectName("warningbtn")
        self.horizontalLayout.addWidget(self.warningbtn)
        self.errorbtn = QtWidgets.QPushButton(logswidget)
        self.errorbtn.setEnabled(True)
        self.errorbtn.setMinimumSize(QtCore.QSize(100, 32))
        self.errorbtn.setMaximumSize(QtCore.QSize(100, 32))
        self.errorbtn.setStyleSheet("QPushButton{\n"
"  padding: 5px 10px;\n"
"  border-radius: 7px;\n"
"  font: 75 9pt \"思源黑体 CN Bold\";\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"  background-color: rgb(237, 113, 97);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.errorbtn.setFlat(True)
        self.errorbtn.setObjectName("errorbtn")
        self.horizontalLayout.addWidget(self.errorbtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.clearbtn = QtWidgets.QPushButton(logswidget)
        self.clearbtn.setStyleSheet("background-color: rgb(237, 113, 97);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"padding: 5px 10px;\n"
"font: 75 9pt \"思源黑体 CN Bold\";")
        self.clearbtn.setDefault(False)
        self.clearbtn.setFlat(False)
        self.clearbtn.setObjectName("clearbtn")
        self.horizontalLayout.addWidget(self.clearbtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.logstext = QtWidgets.QTextBrowser(logswidget)
        self.logstext.setEnabled(True)
        self.logstext.setStyleSheet("QTextBrowser {\n"
"  font:9pt \"思源黑体 CN Regular\";\n"
"}\n"
"\n"
"QScrollBar::vertical {\n"
"    border: none;\n"
"    width: 10px;\n"
"    margin: 3px 0 3px 0;\n"
"}\n"
"\n"
"QScrollBar::horizontal {\n"
"    border: none;\n"
"    height: 10px;\n"
"    margin: 0 3px 0 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical,\n"
"QScrollBar::handle:horizontal {\n"
"    background: #F2F2F2;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 0px solid grey;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 0px solid grey;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: #ffffff;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.logstext.setObjectName("logstext")
        self.verticalLayout.addWidget(self.logstext)

        self.retranslateUi(logswidget)
        QtCore.QMetaObject.connectSlotsByName(logswidget)

    def retranslateUi(self, logswidget):
        _translate = QtCore.QCoreApplication.translate
        logswidget.setWindowTitle(_translate("logswidget", "Form"))
        self.label.setText(_translate("logswidget", "日志级别  "))
        self.infobtn.setText(_translate("logswidget", "INFO"))
        self.warningbtn.setText(_translate("logswidget", "WARNING"))
        self.errorbtn.setText(_translate("logswidget", "ERROR"))
        self.clearbtn.setText(_translate("logswidget", "清空"))
import assets.assets_rc
